version: '3'
services:
  test:
    build:
      context: .
      dockerfile: test/Dockerfile
    network_mode: service:test-redis
    depends_on:
    - test-postgres
  test-redis:
    image: redis
  test-postgres:
    image: postgres
    environment:
    - POSTGRES_USER=storj
    - POSTGRES_PASSWORD=storj-pass

  satellite:
    image: storjlabs/satellite:${VERSION}
    environment:
    - API_KEY=abc123
    - BOOTSTRAP_ADDR=localhost:8080
    - STORJ_CHECKER_QUEUE_ADDRESS=redis://redis:6379/?db=0
    - STORJ_DATABASE=postgres://postgres:postgres@postgres/satellite?sslmode=disable
    - STORJ_LOG_LEVEL=debug
    - STORJ_REPAIRER_QUEUE_ADDRESS=redis://redis:6379/?db=0
    restart: always
    links:
    - redis
    - postgres
    depends_on:
    - redis
    - postgres
  storagenode:
    image: storjlabs/storagenode:${VERSION}
    environment:
    - SATELLITE_ADDR=satellite:7777
    - STORJ_IDENTITY_SERVER_ADDRESS=storagenode:7777
    - STORJ_KADEMLIA_FARMER_EMAIL=hello@storj.io
    - STORJ_KADEMLIA_FARMER_WALLET=0x0000000000000000000000000000000000000000
    - STORJ_LOG_LEVEL=debug
    restart: always
    links:
    - satellite
  gateway:
    image: storjlabs/gateway:${VERSION}
    command: --rs.min-threshold 1 --rs.max-threshold 2 --rs.repair-threshold 1 --rs.success-threshold 1
    environment:
    - API_KEY=abc123
    - SATELLITE_ADDR=satellite:7777
    - STORJ_LOG_LEVEL=debug
    ports:
    - 7777:7777
    restart: always
    links:
    - satellite
    - storagenode
  redis:
    image: redis
  postgres:
    image: postgres:11.1
    environment:
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_DB=satellite
